# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='friends',
            field=models.ManyToManyField(related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
