# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_imagerprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='camera',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='photography_type',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape'), ('nature', 'Nature'), ('family', 'Family'), ('travel', 'Travel'), ('art', 'Art'), ('food', 'Food')], default='nature', max_length=30),
        ),
    ]
