# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='in_album',
            new_name='album',
        ),
    ]
