# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20160411_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ManyToManyField(to='imager_images.Album'),
        ),
    ]
