# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_auto_20160412_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='owner',
        ),
    ]
