# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 00:53
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0007_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(default='photo_files/default_cat.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='photo_files/%Y-%m-%d'),
        ),
    ]
