# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 01:43
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0008_auto_20160416_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(default='photo_files/default_cat.jpg', upload_to=''),
        ),
    ]
