# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0009_auto_20160416_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
    ]
