# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20160420_0351'),
        ('imager_images', '0013_auto_20160420_0210'),
    ]

    operations = [
    ]
